<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="jayesh-PC" name="databaseTesting.databaseTesting" tests="6" failures="0" timestamp="02 Feb 2018 17:02:33 GMT" time="0.476" errors="1">
  <testcase name="dataTest" time="0.329" classname="databaseTesting.databaseTesting"/>
  <testcase name="dataTest" time="0.024" classname="databaseTesting.databaseTesting"/>
  <testcase name="dataTest" time="0.018" classname="databaseTesting.databaseTesting"/>
  <testcase name="dataTest" time="0.049" classname="databaseTesting.databaseTesting">
    <error type="java.sql.SQLException" message="No parameters defined during prepareCall()">
      <![CDATA[java.sql.SQLException: No parameters defined during prepareCall()at com.mysql.jdbc.ServerPreparedStatement.getBinding(ServerPreparedStatement.java:1168)at com.mysql.jdbc.ServerPreparedStatement.setString(ServerPreparedStatement.java:560)at databaseTesting.databaseTesting.dataTest(databaseTesting.java:49)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- dataTest -->
  <testcase name="dataTest" time="0.027" classname="databaseTesting.databaseTesting"/>
  <testcase name="dataTest" time="0.029" classname="databaseTesting.databaseTesting"/>
</testsuite> <!-- databaseTesting.databaseTesting -->
